// Generated by https://quicktype.io

export interface AlbumsProps {
  artist: number;
  albums: AlbumProp[];
}

export interface AlbumProp {
  id:           number;
  name:         string;
  image:        string;
  spotify_url:  string;
  total_tracks: number;
}
