// Generated by https://quicktype.io

export interface SongsProps {
  album: number;
  songs: Array<SongClass>;
}

export interface SongClass {
  id:          number;
  name:        string;
  spotify_url: string;
  preview_url: null | string;
  duration_ms: string;
  explicit:    Explicit;
}

export enum Explicit {
  F = "f",
  T = "t",
}
